blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/idaholab/open_pronghorn/discussions
    about: Ask general questions about OpenPronghorn and discuss with other community members.
